// <auto-generated />
using System;
using System.Text.Json;
using MeningOilam.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeningOilam.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "app_role", new[] { "superadmin", "admin", "member" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "bot_integration_mode", new[] { "media_only", "delete_all", "keep_all" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "gender_type", new[] { "male", "female" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "join_request_status", new[] { "awaiting_relative_choice", "awaiting_relative_confirm", "awaiting_admin_approval", "approved", "rejected", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "member_status", new[] { "pending", "active", "blocked" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "notification_type", new[] { "join_request", "approval_needed", "spam_detected", "error_report", "system" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "relationship_type", new[] { "father", "mother", "son", "daughter", "brother", "sister", "husband", "wife", "uncle_paternal", "uncle_maternal", "aunt_paternal", "aunt_maternal", "cousin_male", "cousin_female", "grandfather", "grandmother", "grandson", "granddaughter", "father_in_law", "mother_in_law", "son_in_law", "daughter_in_law", "brother_in_law", "sister_in_law", "nephew", "niece", "other", "self", "step_father", "step_mother", "step_son", "step_daughter", "half_brother", "half_sister", "great_grandfather", "great_grandmother", "great_grandson", "great_granddaughter", "godfather", "godmother", "family_friend" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "rsvp_status", new[] { "yes", "no", "maybe" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeningOilam.Domain.Entities.ActionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<long?>("ActorTelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_telegram_id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.HasKey("Id")
                        .HasName("pk_action_logs");

                    b.HasIndex("FamilyId", "CreatedAt")
                        .HasDatabaseName("ix_action_logs_family_id_created_at");

                    b.ToTable("action_logs", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.AdminNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.Property<Guid?>("RelatedJoinRequest")
                        .HasColumnType("uuid")
                        .HasColumnName("related_join_request");

                    b.HasKey("Id")
                        .HasName("pk_admin_notifications");

                    b.HasIndex("FamilyId", "IsRead")
                        .HasDatabaseName("ix_admin_notifications_family_id_is_read");

                    b.ToTable("admin_notifications", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.BannedWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsRegex")
                        .HasColumnType("boolean")
                        .HasColumnName("is_regex");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern");

                    b.HasKey("Id")
                        .HasName("pk_banned_words");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_banned_words_family_id");

                    b.ToTable("banned_words", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.BirthdayGreeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("GreeterName")
                        .HasColumnType("text")
                        .HasColumnName("greeter_name");

                    b.Property<long>("GreeterTelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("greeter_telegram_id");

                    b.Property<string>("GreetingText")
                        .HasColumnType("text")
                        .HasColumnName("greeting_text");

                    b.Property<int>("GreetingYear")
                        .HasColumnType("integer")
                        .HasColumnName("greeting_year");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.HasKey("Id")
                        .HasName("pk_birthday_greetings");

                    b.HasIndex("FamilyId", "GreetingYear")
                        .HasDatabaseName("ix_birthday_greetings_family_id_greeting_year");

                    b.HasIndex("MemberId", "GreeterTelegramId", "GreetingYear")
                        .IsUnique()
                        .HasDatabaseName("ix_birthday_greetings_member_id_greeter_telegram_id_greeting_y");

                    b.ToTable("birthday_greetings", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.BotBroadcast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("FailedTargets")
                        .HasColumnType("jsonb")
                        .HasColumnName("failed_targets");

                    b.Property<int>("FailuresCount")
                        .HasColumnType("integer")
                        .HasColumnName("failures_count");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("GenderFilter")
                        .HasColumnType("text")
                        .HasColumnName("gender_filter");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<int>("RecipientsCount")
                        .HasColumnType("integer")
                        .HasColumnName("recipients_count");

                    b.Property<Guid?>("SentByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sent_by_user_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("target");

                    b.HasKey("Id")
                        .HasName("pk_bot_broadcasts");

                    b.ToTable("bot_broadcasts", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.BotIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.Property<string>("BotUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bot_username");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.HasKey("Id")
                        .HasName("pk_bot_integrations");

                    b.HasIndex("FamilyId", "BotUsername")
                        .IsUnique()
                        .HasDatabaseName("ix_bot_integrations_family_id_bot_username");

                    b.ToTable("bot_integrations", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.BotSession", b =>
                {
                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("step");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TelegramId")
                        .HasName("pk_bot_sessions");

                    b.ToTable("bot_sessions", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.DailyMessageBuffer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateOnly>("MessageDate")
                        .HasColumnType("date")
                        .HasColumnName("message_date");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<byte[]>("TextHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("text_hash");

                    b.HasKey("Id")
                        .HasName("pk_daily_message_buffers");

                    b.HasIndex("FamilyId", "MessageDate")
                        .HasDatabaseName("ix_daily_message_buffers_family_id_message_date");

                    b.HasIndex("FamilyId", "TelegramId", "MessageDate", "TextHash")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_message_buffers_family_id_telegram_id_message_date_te");

                    b.ToTable("daily_message_buffers", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsRecurringYearly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring_yearly");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.PrimitiveCollection<int[]>("NotifyDaysBefore")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("notify_days_before");

                    b.Property<bool>("NotifyGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_group");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("FamilyId", "EventAt")
                        .HasDatabaseName("ix_events_family_id_event_at");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.EventRsvp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_event_rsvps");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_event_rsvps_event_id");

                    b.HasIndex("EventId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_rsvps_event_id_member_id");

                    b.ToTable("event_rsvps", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invite_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<long?>("TelegramGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_group_id");

                    b.Property<string>("TelegramGroupTitle")
                        .HasColumnType("text")
                        .HasColumnName("telegram_group_title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ix_families_invite_code");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_families_owner_user_id");

                    b.HasIndex("TelegramGroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_families_telegram_group_id");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("full_name");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<bool>("PhotoIsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("photo_is_private");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<int?>("RelationshipToInviter")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_to_inviter");

                    b.Property<bool>("SentimentOptOut")
                        .HasColumnType("boolean")
                        .HasColumnName("sentiment_opt_out");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_family_members");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_family_members_family_id");

                    b.HasIndex("TelegramId")
                        .HasDatabaseName("ix_family_members_telegram_id");

                    b.HasIndex("FamilyId", "TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_family_members_family_id_telegram_id");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.FamilySettings", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<long?>("AdminNotificationChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("admin_notification_channel_id");

                    b.PrimitiveCollection<string[]>("AllowedLinkDomains")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_link_domains");

                    b.Property<int>("AntiFloodSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("anti_flood_seconds");

                    b.Property<bool>("AntiForward")
                        .HasColumnType("boolean")
                        .HasColumnName("anti_forward");

                    b.Property<bool>("AntiLink")
                        .HasColumnType("boolean")
                        .HasColumnName("anti_link");

                    b.Property<bool>("AutoVideoDownload")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_video_download");

                    b.Property<string>("BackupFrequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup_frequency");

                    b.Property<long?>("BackupTelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("backup_telegram_chat_id");

                    b.Property<TimeOnly>("BirthdayNotifyTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("birthday_notify_time");

                    b.Property<bool>("DeleteJoinLeaveMessages")
                        .HasColumnType("boolean")
                        .HasColumnName("delete_join_leave_messages");

                    b.Property<bool>("EnforceBotOnboarding")
                        .HasColumnType("boolean")
                        .HasColumnName("enforce_bot_onboarding");

                    b.Property<bool>("FeatureBirthdays")
                        .HasColumnType("boolean")
                        .HasColumnName("feature_birthdays");

                    b.Property<bool>("FeatureEvents")
                        .HasColumnType("boolean")
                        .HasColumnName("feature_events");

                    b.Property<bool>("FeatureStatsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("feature_stats_public");

                    b.Property<string>("FemalePhotoVisibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("female_photo_visibility");

                    b.Property<int>("JoinRequestAutoApproveTimeoutHours")
                        .HasColumnType("integer")
                        .HasColumnName("join_request_auto_approve_timeout_hours");

                    b.Property<int>("JoinRequestAutoRejectTimeoutHours")
                        .HasColumnType("integer")
                        .HasColumnName("join_request_auto_reject_timeout_hours");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<long?>("LogTelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("log_telegram_chat_id");

                    b.Property<int?>("LogTopicActions")
                        .HasColumnType("integer")
                        .HasColumnName("log_topic_actions");

                    b.Property<int?>("LogTopicAdmin")
                        .HasColumnType("integer")
                        .HasColumnName("log_topic_admin");

                    b.Property<int?>("LogTopicBackup")
                        .HasColumnType("integer")
                        .HasColumnName("log_topic_backup");

                    b.Property<int?>("LogTopicModeration")
                        .HasColumnType("integer")
                        .HasColumnName("log_topic_moderation");

                    b.Property<bool>("ManageForeignBotMedia")
                        .HasColumnType("boolean")
                        .HasColumnName("manage_foreign_bot_media");

                    b.Property<int>("MaxWarnings")
                        .HasColumnType("integer")
                        .HasColumnName("max_warnings");

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_end");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_start");

                    b.Property<bool>("SoftModerationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("soft_moderation_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("VideoDownloadDeleteOriginal")
                        .HasColumnType("boolean")
                        .HasColumnName("video_download_delete_original");

                    b.Property<string>("WarningAction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("warning_action");

                    b.Property<int>("WelcomeMessageAutoDeleteSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("welcome_message_auto_delete_seconds");

                    b.HasKey("FamilyId")
                        .HasName("pk_family_settings");

                    b.ToTable("family_settings", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.JoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicantFullName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("applicant_full_name");

                    b.Property<string>("ApplicantPhone")
                        .HasColumnType("text")
                        .HasColumnName("applicant_phone");

                    b.Property<long>("ApplicantTelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("applicant_telegram_id");

                    b.Property<string>("ApplicantUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("applicant_username");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<int?>("RelationshipType")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type");

                    b.Property<string>("RelativeHint")
                        .HasColumnType("text")
                        .HasColumnName("relative_hint");

                    b.Property<Guid?>("RelativeMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("relative_member_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_join_requests");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_join_requests_family_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_join_requests_status");

                    b.ToTable("join_requests", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.KinshipSession", b =>
                {
                    b.Property<long>("UserTelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_telegram_id");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("FirstMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_member_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserTelegramId")
                        .HasName("pk_kinship_sessions");

                    b.ToTable("kinship_sessions", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.MemberWarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Auto")
                        .HasColumnType("boolean")
                        .HasColumnName("auto");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<long?>("IssuedByTelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_by_telegram_id");

                    b.Property<Guid?>("IssuedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_user_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("Id")
                        .HasName("pk_member_warnings");

                    b.HasIndex("FamilyId", "MemberId", "CreatedAt")
                        .HasDatabaseName("ix_member_warnings_family_id_member_id_created_at");

                    b.ToTable("member_warnings", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("MessageYear")
                        .HasColumnType("integer")
                        .HasColumnName("message_year");

                    b.Property<Guid?>("SavedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("saved_by_member_id");

                    b.Property<long?>("SavedByTelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("saved_by_telegram_id");

                    b.Property<long?>("SourceChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_chat_id");

                    b.Property<long?>("SourceMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_message_id");

                    b.Property<string>("StorageUrl")
                        .HasColumnType("text")
                        .HasColumnName("storage_url");

                    b.Property<string>("TelegramFileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telegram_file_id");

                    b.HasKey("Id")
                        .HasName("pk_memories");

                    b.HasIndex("FamilyId", "MessageYear")
                        .HasDatabaseName("ix_memories_family_id_message_year");

                    b.ToTable("memories", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.MessagesStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateOnly>("MessageDate")
                        .HasColumnType("date")
                        .HasColumnName("message_date");

                    b.Property<int>("MessagesCount")
                        .HasColumnType("integer")
                        .HasColumnName("messages_count");

                    b.Property<DateTimeOffset?>("SentimentAnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sentiment_analyzed_at");

                    b.Property<decimal?>("SentimentScore")
                        .HasColumnType("numeric")
                        .HasColumnName("sentiment_score");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("Id")
                        .HasName("pk_messages_stats");

                    b.HasIndex("FamilyId", "MessageDate")
                        .HasDatabaseName("ix_messages_stats_family_id_message_date");

                    b.HasIndex("FamilyId", "TelegramId", "MessageDate")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_stats_family_id_telegram_id_message_date");

                    b.ToTable("messages_stats", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.Nomination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("MemberName")
                        .HasColumnType("text")
                        .HasColumnName("member_name");

                    b.Property<decimal?>("MetricValue")
                        .HasColumnType("numeric")
                        .HasColumnName("metric_value");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_nominations");

                    b.HasIndex("FamilyId", "Year", "Category")
                        .IsUnique()
                        .HasDatabaseName("ix_nominations_family_id_year_category");

                    b.ToTable("nominations", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateOnly>("NotifyDate")
                        .HasColumnType("date")
                        .HasColumnName("notify_date");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_notification_logs");

                    b.HasIndex("Kind", "RefId", "NotifyDate")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_logs_kind_ref_id_notify_date");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.PendingAvatarUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("Id")
                        .HasName("pk_pending_avatar_uploads");

                    b.HasIndex("TelegramId")
                        .HasDatabaseName("ix_pending_avatar_uploads_telegram_id");

                    b.ToTable("pending_avatar_uploads", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TelegramUsername")
                        .HasColumnType("text")
                        .HasColumnName("telegram_username");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_telegram_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_user_id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("MemberId1")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id1");

                    b.Property<Guid>("MemberId2")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id2");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type");

                    b.HasKey("Id")
                        .HasName("pk_relationships");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_relationships_family_id");

                    b.HasIndex("MemberId1")
                        .HasDatabaseName("ix_relationships_member_id1");

                    b.HasIndex("MemberId2")
                        .HasDatabaseName("ix_relationships_member_id2");

                    b.HasIndex("MemberId1", "MemberId2", "RelationshipType")
                        .IsUnique()
                        .HasDatabaseName("ix_relationships_member_id1_member_id2_relationship_type");

                    b.ToTable("relationships", null, t =>
                        {
                            t.HasCheckConstraint("ck_relationship_distinct", "member_id1 <> member_id2");
                        });
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.TelegramBotState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<long>("UpdateOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("update_offset");

                    b.HasKey("Id")
                        .HasName("pk_telegram_bot_states");

                    b.ToTable("telegram_bot_states", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.TelegramUpdateRaw", b =>
                {
                    b.Property<long>("UpdateId")
                        .HasColumnType("bigint")
                        .HasColumnName("update_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("UpdateId")
                        .HasName("pk_telegram_updates_raw");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_telegram_updates_raw_processed_at");

                    b.ToTable("telegram_updates_raw", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_user_roles_family_id");

                    b.HasIndex("UserId", "FamilyId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_user_id_family_id_role");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.VideoDownloadJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int>("OriginalMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("original_message_id");

                    b.Property<long>("RequesterTelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("requester_telegram_id");

                    b.Property<int?>("ResultMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("result_message_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int?>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_video_download_jobs");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_video_download_jobs_status");

                    b.HasIndex("FamilyId", "CreatedAt")
                        .HasDatabaseName("ix_video_download_jobs_family_id_created_at");

                    b.ToTable("video_download_jobs", (string)null);
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.EventRsvp", b =>
                {
                    b.HasOne("MeningOilam.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_rsvps_events_event_id");
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.Family", b =>
                {
                    b.HasOne("MeningOilam.Domain.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_families_users_owner_user_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("MeningOilam.Domain.Entities.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.FamilySettings", b =>
                {
                    b.HasOne("MeningOilam.Domain.Entities.Family", "Family")
                        .WithOne("Settings")
                        .HasForeignKey("MeningOilam.Domain.Entities.FamilySettings", "FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_settings_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.Profile", b =>
                {
                    b.HasOne("MeningOilam.Domain.Entities.AppUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("MeningOilam.Domain.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MeningOilam.Domain.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("MeningOilam.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_user_roles_families_family_id");

                    b.HasOne("MeningOilam.Domain.Entities.AppUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("MeningOilam.Domain.Entities.Family", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
