/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUpdatesRouteImport } from './routes/dashboard.updates'
import { Route as DashboardTreeRouteImport } from './routes/dashboard.tree'
import { Route as DashboardStatsRouteImport } from './routes/dashboard.stats'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSentimentRouteImport } from './routes/dashboard.sentiment'
import { Route as DashboardRequestsRouteImport } from './routes/dashboard.requests'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMemoriesRouteImport } from './routes/dashboard.memories'
import { Route as DashboardMembersRouteImport } from './routes/dashboard.members'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardKinshipRouteImport } from './routes/dashboard.kinship'
import { Route as DashboardFamiliesRouteImport } from './routes/dashboard.families'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardBotRouteImport } from './routes/dashboard.bot'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramPollRouteImport } from './routes/api/public/telegram/poll'
import { Route as ApiPublicTelegramMiniappRegisterRouteImport } from './routes/api/public/telegram/miniapp-register'
import { Route as ApiPublicTelegramMiniappAuthRouteImport } from './routes/api/public/telegram/miniapp-auth'
import { Route as ApiPublicCronSentimentAnalysisRouteImport } from './routes/api/public/cron/sentiment-analysis'
import { Route as ApiPublicCronProcessJoinRequestsRouteImport } from './routes/api/public/cron/process-join-requests'
import { Route as ApiPublicCronDailyRemindersRouteImport } from './routes/api/public/cron/daily-reminders'
import { Route as ApiPublicCronAnnualAwardsRouteImport } from './routes/api/public/cron/annual-awards'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUpdatesRoute = DashboardUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTreeRoute = DashboardTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSentimentRoute = DashboardSentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemoriesRoute = DashboardMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKinshipRoute = DashboardKinshipRouteImport.update({
  id: '/kinship',
  path: '/kinship',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFamiliesRoute = DashboardFamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBotRoute = DashboardBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramPollRoute = ApiPublicTelegramPollRouteImport.update({
  id: '/api/public/telegram/poll',
  path: '/api/public/telegram/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramMiniappRegisterRoute =
  ApiPublicTelegramMiniappRegisterRouteImport.update({
    id: '/api/public/telegram/miniapp-register',
    path: '/api/public/telegram/miniapp-register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramMiniappAuthRoute =
  ApiPublicTelegramMiniappAuthRouteImport.update({
    id: '/api/public/telegram/miniapp-auth',
    path: '/api/public/telegram/miniapp-auth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSentimentAnalysisRoute =
  ApiPublicCronSentimentAnalysisRouteImport.update({
    id: '/api/public/cron/sentiment-analysis',
    path: '/api/public/cron/sentiment-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronProcessJoinRequestsRoute =
  ApiPublicCronProcessJoinRequestsRouteImport.update({
    id: '/api/public/cron/process-join-requests',
    path: '/api/public/cron/process-join-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDailyRemindersRoute =
  ApiPublicCronDailyRemindersRouteImport.update({
    id: '/api/public/cron/daily-reminders',
    path: '/api/public/cron/daily-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronAnnualAwardsRoute =
  ApiPublicCronAnnualAwardsRouteImport.update({
    id: '/api/public/cron/annual-awards',
    path: '/api/public/cron/annual-awards',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/bot': typeof DashboardBotRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/families': typeof DashboardFamiliesRoute
  '/dashboard/kinship': typeof DashboardKinshipRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/memories': typeof DashboardMemoriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/sentiment': typeof DashboardSentimentRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/tree': typeof DashboardTreeRoute
  '/dashboard/updates': typeof DashboardUpdatesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/cron/annual-awards': typeof ApiPublicCronAnnualAwardsRoute
  '/api/public/cron/daily-reminders': typeof ApiPublicCronDailyRemindersRoute
  '/api/public/cron/process-join-requests': typeof ApiPublicCronProcessJoinRequestsRoute
  '/api/public/cron/sentiment-analysis': typeof ApiPublicCronSentimentAnalysisRoute
  '/api/public/telegram/miniapp-auth': typeof ApiPublicTelegramMiniappAuthRoute
  '/api/public/telegram/miniapp-register': typeof ApiPublicTelegramMiniappRegisterRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/bot': typeof DashboardBotRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/families': typeof DashboardFamiliesRoute
  '/dashboard/kinship': typeof DashboardKinshipRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/memories': typeof DashboardMemoriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/sentiment': typeof DashboardSentimentRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/tree': typeof DashboardTreeRoute
  '/dashboard/updates': typeof DashboardUpdatesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/cron/annual-awards': typeof ApiPublicCronAnnualAwardsRoute
  '/api/public/cron/daily-reminders': typeof ApiPublicCronDailyRemindersRoute
  '/api/public/cron/process-join-requests': typeof ApiPublicCronProcessJoinRequestsRoute
  '/api/public/cron/sentiment-analysis': typeof ApiPublicCronSentimentAnalysisRoute
  '/api/public/telegram/miniapp-auth': typeof ApiPublicTelegramMiniappAuthRoute
  '/api/public/telegram/miniapp-register': typeof ApiPublicTelegramMiniappRegisterRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/bot': typeof DashboardBotRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/families': typeof DashboardFamiliesRoute
  '/dashboard/kinship': typeof DashboardKinshipRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/memories': typeof DashboardMemoriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/sentiment': typeof DashboardSentimentRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/tree': typeof DashboardTreeRoute
  '/dashboard/updates': typeof DashboardUpdatesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/cron/annual-awards': typeof ApiPublicCronAnnualAwardsRoute
  '/api/public/cron/daily-reminders': typeof ApiPublicCronDailyRemindersRoute
  '/api/public/cron/process-join-requests': typeof ApiPublicCronProcessJoinRequestsRoute
  '/api/public/cron/sentiment-analysis': typeof ApiPublicCronSentimentAnalysisRoute
  '/api/public/telegram/miniapp-auth': typeof ApiPublicTelegramMiniappAuthRoute
  '/api/public/telegram/miniapp-register': typeof ApiPublicTelegramMiniappRegisterRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/sitemap.xml'
    | '/dashboard/bot'
    | '/dashboard/events'
    | '/dashboard/families'
    | '/dashboard/kinship'
    | '/dashboard/logs'
    | '/dashboard/members'
    | '/dashboard/memories'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/sentiment'
    | '/dashboard/settings'
    | '/dashboard/stats'
    | '/dashboard/tree'
    | '/dashboard/updates'
    | '/dashboard/'
    | '/api/public/cron/annual-awards'
    | '/api/public/cron/daily-reminders'
    | '/api/public/cron/process-join-requests'
    | '/api/public/cron/sentiment-analysis'
    | '/api/public/telegram/miniapp-auth'
    | '/api/public/telegram/miniapp-register'
    | '/api/public/telegram/poll'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/dashboard/bot'
    | '/dashboard/events'
    | '/dashboard/families'
    | '/dashboard/kinship'
    | '/dashboard/logs'
    | '/dashboard/members'
    | '/dashboard/memories'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/sentiment'
    | '/dashboard/settings'
    | '/dashboard/stats'
    | '/dashboard/tree'
    | '/dashboard/updates'
    | '/dashboard'
    | '/api/public/cron/annual-awards'
    | '/api/public/cron/daily-reminders'
    | '/api/public/cron/process-join-requests'
    | '/api/public/cron/sentiment-analysis'
    | '/api/public/telegram/miniapp-auth'
    | '/api/public/telegram/miniapp-register'
    | '/api/public/telegram/poll'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/sitemap.xml'
    | '/dashboard/bot'
    | '/dashboard/events'
    | '/dashboard/families'
    | '/dashboard/kinship'
    | '/dashboard/logs'
    | '/dashboard/members'
    | '/dashboard/memories'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/sentiment'
    | '/dashboard/settings'
    | '/dashboard/stats'
    | '/dashboard/tree'
    | '/dashboard/updates'
    | '/dashboard/'
    | '/api/public/cron/annual-awards'
    | '/api/public/cron/daily-reminders'
    | '/api/public/cron/process-join-requests'
    | '/api/public/cron/sentiment-analysis'
    | '/api/public/telegram/miniapp-auth'
    | '/api/public/telegram/miniapp-register'
    | '/api/public/telegram/poll'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicCronAnnualAwardsRoute: typeof ApiPublicCronAnnualAwardsRoute
  ApiPublicCronDailyRemindersRoute: typeof ApiPublicCronDailyRemindersRoute
  ApiPublicCronProcessJoinRequestsRoute: typeof ApiPublicCronProcessJoinRequestsRoute
  ApiPublicCronSentimentAnalysisRoute: typeof ApiPublicCronSentimentAnalysisRoute
  ApiPublicTelegramMiniappAuthRoute: typeof ApiPublicTelegramMiniappAuthRoute
  ApiPublicTelegramMiniappRegisterRoute: typeof ApiPublicTelegramMiniappRegisterRoute
  ApiPublicTelegramPollRoute: typeof ApiPublicTelegramPollRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/updates': {
      id: '/dashboard/updates'
      path: '/updates'
      fullPath: '/dashboard/updates'
      preLoaderRoute: typeof DashboardUpdatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tree': {
      id: '/dashboard/tree'
      path: '/tree'
      fullPath: '/dashboard/tree'
      preLoaderRoute: typeof DashboardTreeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stats': {
      id: '/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof DashboardStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sentiment': {
      id: '/dashboard/sentiment'
      path: '/sentiment'
      fullPath: '/dashboard/sentiment'
      preLoaderRoute: typeof DashboardSentimentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/memories': {
      id: '/dashboard/memories'
      path: '/memories'
      fullPath: '/dashboard/memories'
      preLoaderRoute: typeof DashboardMemoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kinship': {
      id: '/dashboard/kinship'
      path: '/kinship'
      fullPath: '/dashboard/kinship'
      preLoaderRoute: typeof DashboardKinshipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/families': {
      id: '/dashboard/families'
      path: '/families'
      fullPath: '/dashboard/families'
      preLoaderRoute: typeof DashboardFamiliesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bot': {
      id: '/dashboard/bot'
      path: '/bot'
      fullPath: '/dashboard/bot'
      preLoaderRoute: typeof DashboardBotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/poll': {
      id: '/api/public/telegram/poll'
      path: '/api/public/telegram/poll'
      fullPath: '/api/public/telegram/poll'
      preLoaderRoute: typeof ApiPublicTelegramPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/miniapp-register': {
      id: '/api/public/telegram/miniapp-register'
      path: '/api/public/telegram/miniapp-register'
      fullPath: '/api/public/telegram/miniapp-register'
      preLoaderRoute: typeof ApiPublicTelegramMiniappRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/miniapp-auth': {
      id: '/api/public/telegram/miniapp-auth'
      path: '/api/public/telegram/miniapp-auth'
      fullPath: '/api/public/telegram/miniapp-auth'
      preLoaderRoute: typeof ApiPublicTelegramMiniappAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sentiment-analysis': {
      id: '/api/public/cron/sentiment-analysis'
      path: '/api/public/cron/sentiment-analysis'
      fullPath: '/api/public/cron/sentiment-analysis'
      preLoaderRoute: typeof ApiPublicCronSentimentAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/process-join-requests': {
      id: '/api/public/cron/process-join-requests'
      path: '/api/public/cron/process-join-requests'
      fullPath: '/api/public/cron/process-join-requests'
      preLoaderRoute: typeof ApiPublicCronProcessJoinRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-reminders': {
      id: '/api/public/cron/daily-reminders'
      path: '/api/public/cron/daily-reminders'
      fullPath: '/api/public/cron/daily-reminders'
      preLoaderRoute: typeof ApiPublicCronDailyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/annual-awards': {
      id: '/api/public/cron/annual-awards'
      path: '/api/public/cron/annual-awards'
      fullPath: '/api/public/cron/annual-awards'
      preLoaderRoute: typeof ApiPublicCronAnnualAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBotRoute: typeof DashboardBotRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardFamiliesRoute: typeof DashboardFamiliesRoute
  DashboardKinshipRoute: typeof DashboardKinshipRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardMemoriesRoute: typeof DashboardMemoriesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardSentimentRoute: typeof DashboardSentimentRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardTreeRoute: typeof DashboardTreeRoute
  DashboardUpdatesRoute: typeof DashboardUpdatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBotRoute: DashboardBotRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardFamiliesRoute: DashboardFamiliesRoute,
  DashboardKinshipRoute: DashboardKinshipRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardMemoriesRoute: DashboardMemoriesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardSentimentRoute: DashboardSentimentRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStatsRoute: DashboardStatsRoute,
  DashboardTreeRoute: DashboardTreeRoute,
  DashboardUpdatesRoute: DashboardUpdatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicCronAnnualAwardsRoute: ApiPublicCronAnnualAwardsRoute,
  ApiPublicCronDailyRemindersRoute: ApiPublicCronDailyRemindersRoute,
  ApiPublicCronProcessJoinRequestsRoute: ApiPublicCronProcessJoinRequestsRoute,
  ApiPublicCronSentimentAnalysisRoute: ApiPublicCronSentimentAnalysisRoute,
  ApiPublicTelegramMiniappAuthRoute: ApiPublicTelegramMiniappAuthRoute,
  ApiPublicTelegramMiniappRegisterRoute: ApiPublicTelegramMiniappRegisterRoute,
  ApiPublicTelegramPollRoute: ApiPublicTelegramPollRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
