/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRequestsRouteImport } from './routes/dashboard.requests'
import { Route as DashboardMembersRouteImport } from './routes/dashboard.members'
import { Route as DashboardKinshipRouteImport } from './routes/dashboard.kinship'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramPollRouteImport } from './routes/api/public/telegram/poll'
import { Route as ApiPublicCronDailyRemindersRouteImport } from './routes/api/public/cron/daily-reminders'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKinshipRoute = DashboardKinshipRouteImport.update({
  id: '/kinship',
  path: '/kinship',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramPollRoute = ApiPublicTelegramPollRouteImport.update({
  id: '/api/public/telegram/poll',
  path: '/api/public/telegram/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyRemindersRoute =
  ApiPublicCronDailyRemindersRouteImport.update({
    id: '/api/public/cron/daily-reminders',
    path: '/api/public/cron/daily-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/kinship': typeof DashboardKinshipRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/cron/daily-reminders': typeof ApiPublicCronDailyRemindersRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/kinship': typeof DashboardKinshipRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/cron/daily-reminders': typeof ApiPublicCronDailyRemindersRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/kinship': typeof DashboardKinshipRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/cron/daily-reminders': typeof ApiPublicCronDailyRemindersRoute
  '/api/public/telegram/poll': typeof ApiPublicTelegramPollRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/events'
    | '/dashboard/kinship'
    | '/dashboard/members'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/public/cron/daily-reminders'
    | '/api/public/telegram/poll'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/events'
    | '/dashboard/kinship'
    | '/dashboard/members'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/public/cron/daily-reminders'
    | '/api/public/telegram/poll'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/events'
    | '/dashboard/kinship'
    | '/dashboard/members'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/public/cron/daily-reminders'
    | '/api/public/telegram/poll'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicCronDailyRemindersRoute: typeof ApiPublicCronDailyRemindersRoute
  ApiPublicTelegramPollRoute: typeof ApiPublicTelegramPollRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kinship': {
      id: '/dashboard/kinship'
      path: '/kinship'
      fullPath: '/dashboard/kinship'
      preLoaderRoute: typeof DashboardKinshipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/poll': {
      id: '/api/public/telegram/poll'
      path: '/api/public/telegram/poll'
      fullPath: '/api/public/telegram/poll'
      preLoaderRoute: typeof ApiPublicTelegramPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-reminders': {
      id: '/api/public/cron/daily-reminders'
      path: '/api/public/cron/daily-reminders'
      fullPath: '/api/public/cron/daily-reminders'
      preLoaderRoute: typeof ApiPublicCronDailyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardKinshipRoute: typeof DashboardKinshipRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardKinshipRoute: DashboardKinshipRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicCronDailyRemindersRoute: ApiPublicCronDailyRemindersRoute,
  ApiPublicTelegramPollRoute: ApiPublicTelegramPollRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
